version: '3'

networks:
  social_distancing:
    driver: bridge

volumes:
  social_distancing_db:
    driver: local

services:
  social_distancing_db:
    image: postgres:13-alpine
    container_name: social_distancing_db_1
    restart: always
    volumes:
      - social_distancing_db:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: social_distancing
      POSTGRES_USER: social_distancing_user
      POSTGRES_PASSWORD: social_distancing_password
    networks:
      - social_distancing