spring:
  elasticsearch:
    rest:
      uris: http://${ELASTIC_SEARCH_URL:localhost}:9200
      username: elastic
      password: changeme
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:5431}/${DATASOURCE_SCHEMA:social_distancing}
    username: ${DATASOURCE_USER:social_distancing_user}
    password: ${DATASOURCE_PASS:social_distancing_password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        type: trace